version: 3

project:
  locator: SolaceProducts_pubsubplus-kubernetes-quickstart
  id: SolaceProducts_pubsubplus-kubernetes-quickstart
  name: pubsubplus-kubernetes-quickstart
  teams: []
  labels:
    - go

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
