name: Integration Test for FULL Non HA Deployment

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing operator deployment
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          kubectl create ns pubsubplus-operator-system --save-config
          kubectl create secret generic regcred --from-file=.dockerconfigjson=${HOME}/.docker/config.json --type=kubernetes.io/dockerconfigjson -n pubsubplus-operator-system
          make deploy | grep created
          kubectl rollout status deployment pubsubplus-eventbroker-operator -n pubsubplus-operator-system --timeout=30s
          kubectl get crd | grep eventbrokers

      - name: Testing the Operator - nonHA
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=*"
          kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"
          openssl x509 -in tls.crt -out tls.public.pem
          openssl rsa -in tls.key -text > tls.private.pem
          kubectl create secret tls monitoring-tls --key="tls.private.pem" --cert="tls.public.pem"
          kubectl apply -f ci/manifests/eventbroker-nonha.yaml | grep "test-nonha created"
          sleep 5 ; kubectl get all
          kubectl wait --for=condition=ServiceReady eb test-nonha --timeout=120s
          kubectl wait --for=condition=NoWarnings eb test-nonha
          kubectl wait --for=condition=MonitoringReady eb test-nonha
          kubectl wait pods --selector app.kubernetes.io/instance=test-nonha --for condition=Ready
          kubectl get po --show-labels | grep test-nonha | grep "1/1"
          kubectl get po --show-labels | grep test-nonha | grep active=true
          kubectl get sts | grep test-nonha
          kubectl port-forward svc/test-nonha-pubsubplus 55555:55555 &
          kubectl port-forward svc/test-nonha-pubsubplus 55443:55443 &
          sleep 5
          curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
          tar -xvf SDKPERF_C_LINUX64
          pubSubTools/sdkperf_c -cip=tcp://localhost:55555 -mn=1000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
          pubSubTools/sdkperf_c -cip=tcps://localhost:55443 -mn=10000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
          # TODO extract secret BROKER_PASSWORD=$(kubectl get secret test-nonha-pubsubplus-secrets  -o "jsonpath={.data.username_admin_password}" -n default | base64 -d )
          # verify SEMP over TLS
          # Example: curl -k -sS -u admin:$BROKER_PASSWORD https://$url:1943/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>
          sleep 50 ; kubectl get all
          kubectl wait pods --selector app.kubernetes.io/component=metricsexporter --for condition=Ready --timeout=120s
          kubectl port-forward svc/test-nonha-pubsubplus-prometheus-metrics 9628:9628 &
          sleep 1
          curl localhost:9628 | grep Exporter
          # TLS not working on kind, use http for now.
          kubectl delete eventbroker test-nonha | grep deleted